services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env
      - ./app:/var/www/html/app
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hablagrowth.rule=Host(`hablagrowth.online`)"
      - "traefik.http.routers.hablagrowth.entrypoints=websecure"
      - "traefik.http.routers.hablagrowth.tls.certresolver=letsencrypt"
      - "traefik.http.services.hablagrowth.loadbalancer.server.port=80"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.hablagrowth-http.rule=Host(`hablagrowth.online`)"
      - "traefik.http.routers.hablagrowth-http.entrypoints=web"
      - "traefik.http.routers.hablagrowth-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

  mysql:
    image: mysql:8.0
    container_name: hablagrowth_db
    restart: always
    environment:
      MYSQL_DATABASE: hablagrowth
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  db_data:
