services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hablagrowth.rule=Host(`hablagrowth.online`)"
      - "traefik.http.routers.hablagrowth.entrypoints=websecure"
      - "traefik.http.routers.hablagrowth.tls.certresolver=letsencrypt"
      - "traefik.http.services.hablagrowth.loadbalancer.server.port=80"

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true
